export type PrelaunchDirectoryPin = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  postcode?: string;
  address?: string;
  track?: string;
  type?: string;
  mechanic?: string;
  district?: string;
  /** Claimed Unwrapped member — shown differently on map/list. */
  isMember?: boolean;
  /** Public profile slug when isMember. */
  slug?: string;
  category?: string;
};

/** Wave 1 directory pins — Brixton ↔ Herne Hill corridor (food-first + florist/charity/vintage).
 *  Rebuilt from marketing/leads/wave1_corridor_brixton_hernehill.csv.
 *  IDs starting with `lead:` are provisional (no Google Place ID yet).
 */
export const PRELAUNCH_WAVE1_DIRECTORY_PINS: PrelaunchDirectoryPin[] = 
[
  {
    "id": "lead:michael-s-meat-market",
    "name": "Michael's Meat Market",
    "lat": 51.4625,
    "lng": -0.1128,
    "postcode": "SW9 8JL",
    "address": "49 Atlantic Rd",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:ilias-fish-shop",
    "name": "Ilias Fish Shop",
    "lat": 51.4623,
    "lng": -0.1119,
    "postcode": "SW9 8PR",
    "address": "Unit 16, Granville Arcade, Brixton Village",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:carniceria-los-andes",
    "name": "Carniceria Los Andes",
    "lat": 51.4623,
    "lng": -0.1119,
    "postcode": "SW9 8PR",
    "address": "Unit 13, Granville Arcade, Brixton Village",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:harry-otto-sons",
    "name": "Harry Otto & Sons",
    "lat": 51.4624,
    "lng": -0.1118,
    "postcode": "SW9 8PB",
    "address": "Units 22 & 99, Granville Arcade, Brixton Village",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:ramzey-fish-monger",
    "name": "Ramzey Fish Monger",
    "lat": 51.462,
    "lng": -0.1132,
    "postcode": "SW9 8LB",
    "address": "33 Market Row",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:philips-butchers",
    "name": "Philips Butchers",
    "lat": 51.462,
    "lng": -0.1133,
    "postcode": "SW9 8LB",
    "address": "35 Market Row",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:dombey-son",
    "name": "Dombey & Son",
    "lat": 51.46195,
    "lng": -0.11325,
    "postcode": "SW9 8LB",
    "address": "Unit 19 Market Row",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJoxr5r4cFdkgRQfcJW9FRavU",
    "name": "IRENE",
    "lat": 51.462472600000005,
    "lng": -0.1117127,
    "postcode": "SW9 8PS",
    "address": "Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJoyNUSm8EdkgR1K_JxmNLX9s",
    "name": "Atlantic Bakery",
    "lat": 51.4613074,
    "lng": -0.1111775,
    "postcode": "SW9 8PU",
    "address": "The Metropolis, 67 Atlantic Rd, London",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:dugard-daughters",
    "name": "Dugard & Daughters",
    "lat": 51.4532,
    "lng": -0.1015,
    "postcode": "SE24 0EZ",
    "address": "Arch 286, Milkwood Road",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:brixton-foods-halal-meat",
    "name": "Brixton Foods Halal Meat",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JY",
    "address": "9 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:a-k-halal",
    "name": "A K Halal",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JP",
    "address": "21 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:daily-fresh-fish-meat",
    "name": "Daily Fresh Fish & Meat",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JX",
    "address": "16 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:brixton-quality-fresh-fish-seafood",
    "name": "Brixton Quality Fresh Fish & Seafood",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JX",
    "address": "8 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:l-s-mash-sons",
    "name": "L S Mash & Sons",
    "lat": 51.463,
    "lng": -0.114,
    "postcode": "SW9 8HX",
    "address": "Atlantic Road (Brixton market arches)",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:jones-the-butcher",
    "name": "Jones The Butcher",
    "lat": 51.4545,
    "lng": -0.1035,
    "postcode": "SE24 0NT",
    "address": "1 Dulwich Road",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:fish-bargain-warehouse",
    "name": "Fish Bargain Warehouse",
    "lat": 51.461,
    "lng": -0.1235,
    "postcode": "SW2 5SG",
    "address": "32 Acre Lane",
    "track": "end_of_day_food",
    "type": "Fishmonger",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:phil-s-fruit-and-green-grocers",
    "name": "Phil's Fruit and Green Grocers",
    "lat": 51.4622,
    "lng": -0.112,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJd7P8cu0FdkgRkwZisQatl6M",
    "name": "Arapina Bakery - Herne Hill Market",
    "lat": 51.4530062,
    "lng": -0.1025425,
    "postcode": "SE24 0JN",
    "address": "Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJLY9E3nIEdkgRraPhyUlJPsc",
    "name": "Blackbird Bakery Herne Hill",
    "lat": 51.4526827,
    "lng": -0.1022767,
    "postcode": "SE24 0JT",
    "address": "230 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:dough-artisan-bakehouse",
    "name": "Dough Artisan Bakehouse",
    "lat": 51.4532,
    "lng": -0.1014,
    "postcode": "SE24 0EZ",
    "address": "Arch 284, Milkwood Road",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:esme-s-organic-roots",
    "name": "Esme's Organic Roots",
    "lat": 51.4619,
    "lng": -0.1134,
    "postcode": "SW9 8LD",
    "address": "16A Market Row, Coldharbour Lane",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:brixton-foodland",
    "name": "Brixton Foodland",
    "lat": 51.46195,
    "lng": -0.1135,
    "postcode": "SW9 8LD",
    "address": "6 Market Row",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:brixton-cake-shop",
    "name": "Brixton Cake Shop",
    "lat": 51.4535,
    "lng": -0.101,
    "postcode": "SE24 9AA",
    "address": "53-59 Norwood Road",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:bunhead-bakery",
    "name": "Bunhead Bakery",
    "lat": 51.4538,
    "lng": -0.1045,
    "postcode": "SE24 0NG",
    "address": "145 Dulwich Road",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJYcwwmIoDdkgRCC4HcIPpeYM",
    "name": "Christopher's",
    "lat": 51.4533663,
    "lng": -0.0930599,
    "postcode": "SE24 9JY",
    "address": "145 Half Moon Ln, London",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:aries-bakehouse",
    "name": "Aries Bakehouse",
    "lat": 51.4605,
    "lng": -0.122,
    "postcode": "SW2 5TU",
    "address": "99 Acre Lane",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJGYz8qGgEdkgRyO7G5cCHNN0",
    "name": "Guzzl",
    "lat": 51.46221440000001,
    "lng": -0.11192249999999998,
    "postcode": "SW9 8PR",
    "address": "9, Granville Arcade, Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:the-black-farmer-brixton-farmshop",
    "name": "The Black Farmer Brixton Farmshop",
    "lat": 51.46195,
    "lng": -0.1134,
    "postcode": "SW9 8LD",
    "address": "25-27 Market Row",
    "track": "end_of_day_food",
    "type": "Farm shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:cinco-quinas-talho-a-ougue",
    "name": "Cinco Quinas (Talho A\u00e7ougue)",
    "lat": 51.463,
    "lng": -0.1142,
    "postcode": "SW9 8HX",
    "address": "13 Atlantic Road",
    "track": "end_of_day_food",
    "type": "Butcher shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:ma-soda",
    "name": "Ma Soda",
    "lat": 51.4623,
    "lng": -0.1119,
    "postcode": "SW9 8PR",
    "address": "Unit 17, Granville Arcade, Brixton Village",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:l-atelier-patisserie",
    "name": "L'Atelier Patisserie",
    "lat": 51.4619,
    "lng": -0.1132,
    "postcode": "SW9 8LB",
    "address": "Market Row",
    "track": "end_of_day_food",
    "type": "Bakery",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:aziz-green-grocers",
    "name": "Aziz Green Grocers",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JY",
    "address": "15 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:danny-s-greengrocers",
    "name": "Danny's Greengrocers",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JP",
    "address": "19 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:abdul-s-fruit-veg",
    "name": "Abdul's Fruit & Veg",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JP",
    "address": "41 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:asad-nasseri-quality-food-veg",
    "name": "Asad Nasseri Quality Food & Veg",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JP",
    "address": "45 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:k-m-fresh-fruit-vegetables",
    "name": "K.M Fresh Fruit & Vegetables",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JP",
    "address": "25 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:seasons-of-england",
    "name": "Seasons of England",
    "lat": 51.452,
    "lng": -0.0985,
    "postcode": "SE24 0HY",
    "address": "292 Milkwood Road",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:the-sicilian-delicatessen",
    "name": "The Sicilian Delicatessen",
    "lat": 51.4529,
    "lng": -0.1022,
    "postcode": "SE24 0JN",
    "address": "313 Railton Road",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:lulu-s",
    "name": "Lulu's",
    "lat": 51.4532,
    "lng": -0.1025,
    "postcode": "SE24 0JP",
    "address": "291 Railton Road",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:raina-santa-portuguese-foods",
    "name": "Raina Santa Portuguese Foods",
    "lat": 51.4532,
    "lng": -0.1015,
    "postcode": "SE24 0JF",
    "address": "Milkwood Road",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:latin-caribbean-food-store",
    "name": "Latin & Caribbean Food Store",
    "lat": 51.4622,
    "lng": -0.1117,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJtUniX3UEdkgRE6dJFifiUgc",
    "name": "Cafe' del Cuore (cafe' of the heart)",
    "lat": 51.4532856,
    "lng": -0.0937643,
    "postcode": "SE24 9JY",
    "address": "135 Half Moon Ln, London",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:gusto-italiano",
    "name": "Gusto Italiano",
    "lat": 51.4533,
    "lng": -0.0937,
    "postcode": "SE24 9JY",
    "address": "135 Half Moon Lane",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:nour-cash-carry",
    "name": "Nour Cash & Carry",
    "lat": 51.4621,
    "lng": -0.112,
    "postcode": "SW9 8PR",
    "address": "Granville Arcade",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:the-flower-lady",
    "name": "The Flower Lady",
    "lat": 51.4532,
    "lng": -0.1025,
    "postcode": "SE24 0JP",
    "address": "297 Railton Road",
    "track": "flowers",
    "type": "Florist",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "lead:salon-delicatessen",
    "name": "Salon Delicatessen",
    "lat": 51.4619,
    "lng": -0.113,
    "postcode": "SW9 8LB",
    "address": "Market Row",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJazsTkEoFdkgRoSYdM6W04Dk",
    "name": "Brothers Green The Florist",
    "lat": 51.4526557,
    "lng": -0.1011126,
    "postcode": "SE24 9HU",
    "address": "4-6 Half Moon Ln, London",
    "track": "flowers",
    "type": "Florist",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "lead:my-village-shop",
    "name": "My Village Shop",
    "lat": 51.4628,
    "lng": -0.1135,
    "postcode": "SW9 8HX",
    "address": "Electric Ave & Atlantic Rd",
    "track": "end_of_day_food",
    "type": "Greengrocer",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:royal-trinity-hospice-brixton",
    "name": "Royal Trinity Hospice Brixton",
    "lat": 51.4628,
    "lng": -0.1148,
    "postcode": "SW9 8EQ",
    "address": "494 Brixton Road",
    "track": "charity",
    "type": "Thrift store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:il-sovrano",
    "name": "Il Sovrano",
    "lat": 51.4505,
    "lng": -0.108,
    "postcode": "SW2",
    "address": "Tulse Hill / Brixton Water Lane end",
    "track": "end_of_day_food",
    "type": "Deli",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:traid-brixton",
    "name": "TRAID Brixton",
    "lat": 51.461,
    "lng": -0.1235,
    "postcode": "SW2 5SG",
    "address": "2 Acre Lane",
    "track": "charity",
    "type": "Thrift store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:leona-vintage",
    "name": "Leona Vintage",
    "lat": 51.4623,
    "lng": -0.1119,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:champagne-fromage-brixton",
    "name": "Champagne + Fromage Brixton",
    "lat": 51.462,
    "lng": -0.112,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:oxfam-herne-hill",
    "name": "Oxfam Herne Hill",
    "lat": 51.4531,
    "lng": -0.1002,
    "postcode": "SE24 9HU",
    "address": "20 Half Moon Lane",
    "track": "charity",
    "type": "Thrift store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "lead:jarr-market",
    "name": "Jarr Market",
    "lat": 51.4531,
    "lng": -0.1,
    "postcode": "SE24 9JU",
    "address": "19 Half Moon Lane",
    "track": "end_of_day_food",
    "type": "Zero waste shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:barnardo-s-brixton",
    "name": "Barnardo's Brixton",
    "lat": 51.4615,
    "lng": -0.1155,
    "postcode": "SW9 7AY",
    "address": "406-408 Brixton Road",
    "track": "charity",
    "type": "Thrift store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:british-heart-foundation-brixton-furniture-elect",
    "name": "British Heart Foundation Brixton Furniture & Electrical",
    "lat": 51.4609,
    "lng": -0.123,
    "postcode": "SW2 5SP",
    "address": "36-38 Acre Lane",
    "track": "charity",
    "type": "Thrift store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:sloe-vintage",
    "name": "Sloe Vintage",
    "lat": 51.4624,
    "lng": -0.112,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJhVH6cd4FdkgRyia2Nx3pbsI",
    "name": "Lark Herne Hill",
    "lat": 51.452752,
    "lng": -0.1017705,
    "postcode": "SE24 0JN",
    "address": "317 Railton Rd, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "lead:brixton-bazaar",
    "name": "Brixton Bazaar",
    "lat": 51.462,
    "lng": -0.1125,
    "postcode": "SW9 8LN",
    "address": "437 Coldharbour Lane",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJZcf8qGgEdkgRriN3xuKHP08",
    "name": "Full Moon Designs",
    "lat": 51.462235500000006,
    "lng": -0.1119549,
    "postcode": "SW9 8PR",
    "address": "8, Brixton Village, First Avenue, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:ali-food-store",
    "name": "Ali Food Store",
    "lat": 51.4623,
    "lng": -0.1119,
    "postcode": "SW9 8PR",
    "address": "Units 83-84, Granville Arcade, Brixton Village",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJFWXxL3MEdkgR-Sk4D3wiX6A",
    "name": "Wish",
    "lat": 51.4525698,
    "lng": -0.1018882,
    "postcode": "SE24 0JT",
    "address": "238 Railton Rd, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "lead:circus",
    "name": "Circus",
    "lat": 51.4623,
    "lng": -0.1118,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:sierra-leone-groceries",
    "name": "Sierra Leone Groceries",
    "lat": 51.4622,
    "lng": -0.1118,
    "postcode": "SW9 8PR",
    "address": "Brixton Village",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJEe-5Sm8EdkgR9ze50_3dJ7I",
    "name": "Diverse",
    "lat": 51.4617946,
    "lng": -0.11276589999999999,
    "postcode": "SW9 8LF",
    "address": "390 Coldharbour Ln, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJxy6Lq2gEdkgRLu6IXLr7KNc",
    "name": "Rachel & Malika's",
    "lat": 51.462680299999995,
    "lng": -0.11189579999999999,
    "postcode": "SW9 8PR",
    "address": "Granville Arcade, Coldharbour Ln, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:nyame-bekyare",
    "name": "Nyame & Bekyare",
    "lat": 51.46195,
    "lng": -0.1133,
    "postcode": "SW9 8LB",
    "address": "Unit 17, Electric Lane, Brixton Village",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJMbFoacQFdkgReKzUs9DYqSE",
    "name": "Brothers Green Vintage",
    "lat": 51.452655899999996,
    "lng": -0.1011131,
    "postcode": "SE24 9HU",
    "address": "4 Half Moon Ln, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "ChIJy6FSmoup2EcRUYrFLM0dels",
    "name": "Lalune London",
    "lat": 51.4619448,
    "lng": -0.11341769999999998,
    "postcode": "SW9 8LB",
    "address": "Lalune, 24 Market Row, London",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:africa-shopping-centre",
    "name": "Africa Shopping Centre",
    "lat": 51.4626,
    "lng": -0.1138,
    "postcode": "SW9 8JR",
    "address": "24-26 Electric Avenue",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:brixton-wholefoods",
    "name": "Brixton Wholefoods",
    "lat": 51.4614,
    "lng": -0.1113,
    "postcode": "SW9 8PU",
    "address": "59 Atlantic Road",
    "track": "end_of_day_food",
    "type": "Specialty food",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "lead:quirky-dovetail",
    "name": "Quirky Dovetail",
    "lat": 51.4608,
    "lng": -0.121,
    "postcode": "SW2 5TN",
    "address": "61 Acre Lane",
    "track": "fashion",
    "type": "Clothing store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJD-64OXMEdkgRC456qxynh8Q",
    "name": "Wild + Lees",
    "lat": 51.4526037,
    "lng": -0.1011478,
    "postcode": "SE24 9HU",
    "address": "2 Half Moon Ln, London",
    "track": "wine",
    "type": "Liquor store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "ChIJ30NQAHAFdkgRyEiuSYFeISI",
    "name": "Bottle + Rye",
    "lat": 51.4617467,
    "lng": -0.11316980000000001,
    "postcode": "SW9 8LD",
    "address": "Ground Floor, 404-406 Market Row, London",
    "track": "wine",
    "type": "Liquor store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJ09CeNW8EdkgR5JUbLsXdylg",
    "name": "Ghost Whale",
    "lat": 51.460936,
    "lng": -0.1112,
    "postcode": "SW9 8PX",
    "address": "70 Atlantic Rd, London",
    "track": "wine",
    "type": "Liquor store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJjYfNROgFdkgRU8pS_rm186U",
    "name": "Round Table Books",
    "lat": 51.4622896,
    "lng": -0.1120188,
    "postcode": "SW9 8PR",
    "address": "Brixton Village, 10-11 Granville Arcade, Coldharbour Ln, London",
    "track": "books",
    "type": "Book store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJCSCpJnMEdkgRLDbrqeB3B5I",
    "name": "Herne Hill Books",
    "lat": 51.453256599999996,
    "lng": -0.102883,
    "postcode": "SE24 0LY",
    "address": "289 Railton Rd, London",
    "track": "books",
    "type": "Book store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "ChIJq6qqqmcEdkgR2tfsTEIov5I",
    "name": "Beautiful Books",
    "lat": 51.4632139,
    "lng": -0.1134521,
    "postcode": "SW9 8PD",
    "address": "24 Brixton Station Rd, London",
    "track": "books",
    "type": "Book store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJ1fPOjmgEdkgRRYpRE3705TM",
    "name": "BookMongers",
    "lat": 51.4614986,
    "lng": -0.1138935,
    "postcode": "SW9 8LN",
    "address": "439 Coldharbour Ln, London",
    "track": "books",
    "type": "Book store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "ChIJudsopR4FdkgRxoV1IRkEb4I",
    "name": "The Paper Cat Children's Bookshop",
    "lat": 51.453076499999995,
    "lng": -0.0998852,
    "postcode": "SE24 9JU",
    "address": "25 Half Moon Ln, London",
    "track": "books",
    "type": "Book store",
    "mechanic": "curated_object",
    "district": "SE24"
  },
  {
    "id": "ChIJ51yHpd8FdkgRL59IKZvwtoY",
    "name": "ABLE REBIRTH RECORDS",
    "lat": 51.465320899999995,
    "lng": -0.1030208,
    "postcode": "SW9 8RR",
    "address": "0 1, Green Man Court, 229 Coldharbour Ln, London",
    "track": "books",
    "type": "Book store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:bhf-brixton-acre-lane",
    "name": "BHF Brixton Acre Lane",
    "lat": 51.4609,
    "lng": -0.123,
    "postcode": "SW2 5SP",
    "address": "36-38 Acre Lane",
    "track": "charity",
    "type": "Thrift store",
    "mechanic": "curated_object",
    "district": "SW9"
  },
  {
    "id": "lead:off-the-cuff",
    "name": "Off the Cuff",
    "lat": 51.4532,
    "lng": -0.102,
    "postcode": "SE24 0JN",
    "address": "Arch 645, 301-303 Railton Rd",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJAYMKmmgEdkgR8bMfQkwp1UM",
    "name": "Express Cafe",
    "lat": 51.462055899999996,
    "lng": -0.11329679999999999,
    "postcode": "SW9 8LB",
    "address": "15-17 Market Row, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJYZZ0MWYEdkgRnPbmSc_T7dI",
    "name": "Cafe Rio",
    "lat": 51.463049299999994,
    "lng": -0.11309840000000002,
    "postcode": "SW9 8PE",
    "address": "30 Brixton Station Rd, London",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJ96NMq1oFdkgR1iwCsNI28Vg",
    "name": "Lala Cafe Brixton",
    "lat": 51.463049299999994,
    "lng": -0.11309840000000002,
    "postcode": "SW9 8PE",
    "address": "30 Brixton Station Rd, London",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJwXZTXy8FdkgRw9Lqak1DB_0",
    "name": "No.61",
    "lat": 51.461638199999996,
    "lng": -0.11144559999999999,
    "postcode": "SW9 8PU",
    "address": "The Metropolis, 61 Atlantic Rd, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJ9WToChgFdkgR_44-0v7T-Uk",
    "name": "Brixtonia",
    "lat": 51.4638201,
    "lng": -0.1131252,
    "postcode": "SW9 8PB",
    "address": "19 Brixton Station Rd, London",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJYT-R-xcFdkgRrmH0y2OONzg",
    "name": "F. Mondays Coffee",
    "lat": 51.4615314,
    "lng": -0.114717,
    "postcode": "SW2 1JG",
    "address": "436 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SW2"
  },
  {
    "id": "ChIJdRyTKQ0FdkgRQkgiNJ1n388",
    "name": "Sendero Specialty Coffee Brixton",
    "lat": 51.46329540000001,
    "lng": -0.11464049999999999,
    "postcode": "SW9 8HX",
    "address": "1 Atlantic Rd, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJn3ZmNG8EdkgRPZBvrtj9iZI",
    "name": "PARISSI",
    "lat": 51.4608369,
    "lng": -0.11122430000000001,
    "postcode": "SW9 8PX",
    "address": "76 Atlantic Rd, London",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJMQkh54IFdkgRtCH3P3FQxBQ",
    "name": "Koala Coffee & Ice Cream",
    "lat": 51.4585182,
    "lng": -0.1093036,
    "postcode": "SE24 0LF",
    "address": "64 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:cuppo-bubbo",
    "name": "Cuppo Bubbo",
    "lat": 51.453,
    "lng": -0.102,
    "postcode": "SE24 9LR",
    "address": "167 Herne Hill",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJ1WQWdlgFdkgRfzf9HS19rsw",
    "name": "Sesami",
    "lat": 51.452880799999996,
    "lng": -0.102056,
    "postcode": "SE24 0JN",
    "address": "307 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJYZdOSd8FdkgRhaN1Xb1louI",
    "name": "Perks & White coffee, Herne Hill Station",
    "lat": 51.4530992,
    "lng": -0.1022043,
    "postcode": "SE24 0JW",
    "address": "Station Ticket Hall, Herne Hill, Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:goodness-cafe-by-harry-s-kitchen",
    "name": "Goodness! Cafe by Harry's Kitchen",
    "lat": 51.4532,
    "lng": -0.1015,
    "postcode": "SE24 0EZ",
    "address": "288 Milkwood Road",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:arcade-coffee-co",
    "name": "Arcade Coffee & Co",
    "lat": 51.4532,
    "lng": -0.1015,
    "postcode": "SE24 0HH",
    "address": "Milkwood Road",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:oracles-juice-bar",
    "name": "Oracles Juice Bar",
    "lat": 51.4623,
    "lng": -0.1119,
    "postcode": "SW9 8PR",
    "address": "Unit 90, Granville Arcade, Brixton Village",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJOaTXQzYFdkgRoxXKaqVQCH8",
    "name": "Macatia and Coffee",
    "lat": 51.4525869,
    "lng": -0.10154439999999999,
    "postcode": "SE24 9JU",
    "address": "1A Half Moon Ln, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:healthy-eaters",
    "name": "Healthy Eaters",
    "lat": 51.46195,
    "lng": -0.1134,
    "postcode": "SW9 8LD",
    "address": "Market Row, Brixton Village",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJf0U5FqEFdkgRewELzcV1YJQ",
    "name": "Mino Pottery Painting & Cafe",
    "lat": 51.4527588,
    "lng": -0.10029669999999999,
    "postcode": "SE24 9HU",
    "address": "16 Half Moon Ln, London",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:the-parlour",
    "name": "The Parlour",
    "lat": 51.4535,
    "lng": -0.101,
    "postcode": "SE24 9AA",
    "address": "19 Norwood Road",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:steve-s-cafe",
    "name": "Steve's Cafe",
    "lat": 51.4535,
    "lng": -0.101,
    "postcode": "SE24 9AA",
    "address": "71 Norwood Road",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:elsewhere-coffee",
    "name": "Elsewhere Coffee",
    "lat": 51.4531,
    "lng": -0.1,
    "postcode": "SE24 9JU",
    "address": "1A Half Moon Lane",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJiR62zSYFdkgR0pIMP_uzh5c",
    "name": "Flo's",
    "lat": 51.4530976,
    "lng": -0.09992,
    "postcode": "SE24 9JU",
    "address": "23 Half Moon Ln, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJuc7P7JMFdkgRsy0UqO0RtW0",
    "name": "Railton Lounge",
    "lat": 51.455655199999995,
    "lng": -0.1051583,
    "postcode": "SE24 0JX",
    "address": "126 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "lead:sam-s-cafe",
    "name": "Sam's Cafe",
    "lat": 51.4608,
    "lng": -0.1225,
    "postcode": "SW2 5TN",
    "address": "85 Acre Lane",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJ-9VzxRkFdkgR73zxMJYBB2E",
    "name": "The Travel Caff\u00e9",
    "lat": 51.465641999999995,
    "lng": -0.10333729999999999,
    "postcode": "SW9 8SD",
    "address": "228 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJSXuxcDwFdkgRaE9Zw_fp0NA",
    "name": "Four Boroughs - Coldharbour Works",
    "lat": 51.46474,
    "lng": -0.10240669999999999,
    "postcode": "SW9 8RR",
    "address": "Four Boroughs, Coldharbour Works, 245a Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJCb3vp6UFdkgRC05CgJ_WDj0",
    "name": "LJ Grind",
    "lat": 51.4662545,
    "lng": -0.1017893,
    "postcode": "SW9 8SA",
    "address": "204 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJD1U3GgAFdkgRUBYUsb4Svqs",
    "name": "Viv\u2019s Coffee",
    "lat": 51.466487799999996,
    "lng": -0.1012879,
    "postcode": "SE5 9QH",
    "address": "198 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Coffee shop",
    "mechanic": "end_of_day_food",
    "district": "SE5"
  },
  {
    "id": "lead:sessa",
    "name": "Sessa",
    "lat": 51.4529,
    "lng": -0.1023,
    "postcode": "SE24 0JT",
    "address": "222 Railton Road",
    "track": "end_of_day_food",
    "type": "Cafe",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJW6ANzfcFdkgRDeYV_Acg_70",
    "name": "ALL ROADS BRIXTON",
    "lat": 51.462154899999994,
    "lng": -0.1125071,
    "postcode": "SW9 8JN",
    "address": "44 Atlantic Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJE0IsMAAFdkgR-Mi1d2U6tkk",
    "name": "La Taberna Del Sabor",
    "lat": 51.4622666,
    "lng": -0.1120141,
    "postcode": "SW9 8JL",
    "address": "47 Atlantic Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJHTZz450FdkgRO3tGhl80fCc",
    "name": "Cantinho Mineiro",
    "lat": 51.462365,
    "lng": -0.11180989999999999,
    "postcode": "SW9 8PS",
    "address": "Granville Arcade, Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJpSpJuOkFdkgRTNgWzwAio6s",
    "name": "Danclair's Kitchen",
    "lat": 51.462493099999996,
    "lng": -0.11181350000000001,
    "postcode": "SW9 8PS",
    "address": "67-68, Granville Arcade, Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJbcqu1ugFdkgRrye3IrI2igI",
    "name": "Herne Hill Foods",
    "lat": 51.4524991,
    "lng": -0.1018954,
    "postcode": "SE24 0JT",
    "address": "240 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJ35SN4HIEdkgR2J0HhGI6RMo",
    "name": "Llewelyn's",
    "lat": 51.453288199999996,
    "lng": -0.10274119999999999,
    "postcode": "SE24 0JP",
    "address": "293-295 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJAc87YOUFdkgRMNPyR4LIO6k",
    "name": "La Nonna (Pasta fresca)",
    "lat": 51.4620251,
    "lng": -0.1133031,
    "postcode": "SW9 8LB",
    "address": "7 Market Row, London",
    "track": "end_of_day_food",
    "type": "Italian restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJS1f5qmgEdkgRuHWqMQ13CfA",
    "name": "OKAN Brixton Village",
    "lat": 51.462564099999994,
    "lng": -0.11167149999999999,
    "postcode": "SW9 8PS",
    "address": "39, Brixton Village, Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Japanese restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJJfRNomgEdkgRyBeLhezr9Ak",
    "name": "Sarava Creperie Bar & Cafe",
    "lat": 51.462469899999995,
    "lng": -0.11161639999999999,
    "postcode": "SW9 8PS",
    "address": "41-42, Market, Brixton Village, Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Dessert shop",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJvc8XWAAFdkgRtom_Oiz97KI",
    "name": "Arepa & Co Venezuelan Restaurant Brixton",
    "lat": 51.4618426,
    "lng": -0.11329149999999999,
    "postcode": "SW9 8LD",
    "address": "14B, C, Market Row, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJhRy5kZoFdkgRUS1z8xdVL1g",
    "name": "COLIBRI RESTAURANT & BAR",
    "lat": 51.461625,
    "lng": -0.1139457,
    "postcode": "SW9 8LF",
    "address": "426 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJFx4BHwAFdkgRq_bGAxvg-Jk",
    "name": "Brixton Spritz",
    "lat": 51.4633798,
    "lng": -0.11339800000000001,
    "postcode": "SW9 8QQ",
    "address": "21 Brixton Station Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJ84-rRqcFdkgRkRB5V53Pn48",
    "name": "Kalandula Brixton",
    "lat": 51.4635064,
    "lng": -0.1141441,
    "postcode": "SW9 8PA",
    "address": "5 Brixton Station Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJ5U5qeGUEdkgR0IzkMt4IPEc",
    "name": "OKAN Brixton East",
    "lat": 51.462892599999996,
    "lng": -0.10860629999999999,
    "postcode": "SW9 8QH",
    "address": "338 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Japanese restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJ-_EH5IAFdkgRYGgf3Wr0rXw",
    "name": "Whole Beast",
    "lat": 51.462927,
    "lng": -0.1085376,
    "postcode": "SW9 8QH",
    "address": "336 Coldharbour Ln, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SW9"
  },
  {
    "id": "ChIJx79BMgAFdkgRexmLQzhya-k",
    "name": "Maureen's Brixton Kitchen",
    "lat": 51.458850299999995,
    "lng": -0.1096509,
    "postcode": "SE24 0LF",
    "address": "52 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJcS9s55YDdkgRF89wWceXOvY",
    "name": "West 16th",
    "lat": 51.453338599999995,
    "lng": -0.09370189999999999,
    "postcode": "SE24 9JY",
    "address": "137 Half Moon Ln, London",
    "track": "end_of_day_food",
    "type": "Restaurant",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  },
  {
    "id": "ChIJTVXxdm4EdkgR4ppvLr9O4Ks",
    "name": "Kai Hung",
    "lat": 51.457279,
    "lng": -0.107482,
    "postcode": "SE24 0LD",
    "address": "88 Railton Rd, London",
    "track": "end_of_day_food",
    "type": "Takeout restaurant",
    "mechanic": "end_of_day_food",
    "district": "SE24"
  }
];
